# configs/train_config.yaml

paths:
  output_dir: "/home/en540-lludwig2/ProMDLM/bulk_gen/fulldiff_TEST"
  csv_save_name: "fulldiff_gen_TEST.csv"

model:
  path_weights: 'training_results/L_scheme_1_full_lysozyme/L_scheme_1_full_lysozyme_weights.pth'
  device: 'cuda'
  length: 150
  num_gen: 10
  temp: 1.0
