# configs/train_config.yaml

paths:
  train_file: "/home/jtso3/ghassan/ProMDLM/data/lyzozyme_train.pkl"
  val_file: "/home/jtso3/ghassan/ProMDLM/data/lyzozyme_val.pkl"
  pretrained_model_cfg: "configs/config_150m.yaml"
  pretrained_model_name: "facebook/esm2_t30_150M_UR50D"
  output_dir: "/home/jtso3/ghassan/ProMDLM/training_results/one_epoch_run"
  job_name: "one_epoch_run"

training:
  device: "cuda:0"
  learning_rate: 0.0001
  batch_size: 32
  epochs: 5
  max_timesteps: 100
  seq_len: 282
  vocab_size: 33
  weight_decay: 1e-5
  scheme: 2
  validation: false